### ISSUE TITLE
[Bug/Feature?]`download` doesn't support `--skip-broken`

### ISSUE THREAD

**Issue by mtalexan** [rpm-software-management/dnf-plugins-core#513]
Running a command like:

```
dnf download {...} --resolve --all-deps --exclude=basesystem --skip-broken curl
```

ignores the `--skip-broken` and errors out on the missing `basesystem` requirement being unmet.  As I understand it, the `--skip-broken` is explicitly supposed to prevent this type of error and allow it to continue normally.

---

My use case is that I would like to download a package and all it's recursive install dependencies, for an air-gapped system from another similar-but-not-exactly-the-same system.  I don't want to include the portions of the dependency tree that I know in advance are already present on the air-gapped system, like `basesystem`.

**Comment by m-blaha** [comment]
This is tricky. You are right that the `download` command does not support the `--skip-broken` switch. But the problem is, that to resolve all `curl` package dependencies we basically "pretend" we have an empty system, try to install the `curl` package there, and then download every package in the transaction.  But if you add `--exclude=basesystem`, transaction resolution fails (because `basesystem` is one of `curl` dependencies). Unfortunately, we do not get something like a "partial transaction" from the solver; we don't get any transaction at all. Which in turn means dnf does not know what to download.

So the basic `--skip-broken`  support for the `download` command might mean, that instead of raising an error, the `curl` package (and it's entire dependency tree) would be skipped from downloading. Which is not exactly what you need, I guess.

**Comment by mtalexan** [comment]
I haven't used it during a regular `install`, but does the `--skip-broken` indicate that any trees missing dependencies should be skipped, or that it should simply ignore a missing dependency when encountered in a tree and install anything it does know about?  I assumed the latter.  If that's how it worked, then I would think the `download` could have just passed the it thru to the `install --download-only --destdir` command that it sounds like it's effectively running in the background.

**Comment by m-blaha** [comment]
Actually the former. DNF does not allow you to install packages with missing dependencies. You can do it using underlying rpm but not with DNF. And `download --resolve` works similarly - either you can download the whole dependency tree, or it fails and does not download anything.

**Comment by mtalexan** [comment]
Well dang.  Digging into the code more, it appears all the logic is in `python-hawkey` and/or `libdnf` to do any dependency tree operations.  Since my primary issue is wanting to pre-prune based on what's already available on a target system different from the one I'm currently on, it appears I'm out of luck because that's not possible from `python-hawkey`.
